### ISSUE TITLE
NullReferenceException caused by ConfigureAwait.Fody

### ISSUE THREAD

**Issue by Storm-BE** [Fody/ConfigureAwait#537]
#### Describe the issue

The following code throws a `NullReferenceException` when processed by ConfigureAwait.Fody. 
It finishes successfully when the weaver is disabled.

```C#
Console.WriteLine("Hello, World!");
string? someString = null;
await (someString == "anyValue" ? SomeMethodAsync() : SomeMethodAsync());
Console.WriteLine("Finished successfully!");

static Task SomeMethodAsync()
{
    return Task.CompletedTask;
}
```
It does not throw when I save the Task to a local variable and `await` in a separate statement

```C#
var toAwait = (someString == "anyValue" ? SomeMethodAsync() : SomeMethodAsync());
await toAwait;
```

Typical stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Tasks.Task.AddTaskContinuationComplex(Object tc, Boolean addBeforeOthers)
   at System.Threading.Tasks.Task.AddTaskContinuation(Object tc, Boolean addBeforeOthers)
   at System.Threading.Tasks.Task.UnsafeSetContinuationForAwait(IAsyncStateMachineBox stateMachineBox, Boolean continueOnCapturedContext)
   at System.Runtime.CompilerServices.TaskAwaiter.UnsafeOnCompletedInternal(Task task, IAsyncStateMachineBox stateMachineBox, Boolean continueOnCapturedContext)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitUnsafeOnCompleted[TAwaiter](TAwaiter& awaiter, IAsyncStateMachineBox box)
   at Program.<Main>$(String[] args) in C:\Repos\experiments\configureawait-fody-nre-bug-repro\Program.cs:line 3
   at Program.<Main>(String[] args)
```

I'm running:
* dotnet 6
* Fody 6.7.0
* ConfigureAwait.Fody 3.3.2

#### Minimal Repro
Can be found here: https://github.com/Storm-BE/configureawait-fody-nre-bug-repro

#### Make an effort to fix the bug
If I find some time I hope to have a look at this myself

**Comment by LeVraiSylvain** [comment]
dotnet 10
Fody 6.9.3
ConfigureAwait.Fody 3.4.0


I can confirm this is still reproducible.

Given the following code:

```csharp
public async static Task Test2Async(string arg1)
{
    await (arg1 == "anyValue" ? Task.Delay(1000) : Task.Delay(2000));
}
```
After weaving, the generated code shows inconsistent behavior depending on the branch.
From IL / decompiled view:
- One branch uses ConfigureAwait(false) correctly
- The other branch does not (it directly awaits Task.Delay(...))

Additionally, the method is transformed into **unsafe**, even though the original code is safe. This is unexpected and suggests that the weaving introduces low-level constructs (ref / awaitable handling).

This can be seen in the attached screenshot.

It looks like the conditional expression (?:) leads to different weaving results depending on how the compiler lowers the code.

Is this a known limitation of the weaver when dealing with conditional expressions or certain lowered async patterns?

<img width="1986" height="2316" alt="Image" src="https://github.com/user-attachments/assets/e48e1916-833e-4db0-aeb8-07bbd9a6e25e" />
